### PR TITLE
Adapted to Gymnasium

### PR DESCRIPTION
**Pull request by AlexPasqua**
I made a few modifications as I got errors when trying to run the script.
In particular:
- Added extra returned value (ingored with "_") to `env.step` and to `env.reset`
- Passed the seed to reset method and removed from `set_seed`
  - I'm not sure `set_seed` is still needed though, we might remove it completely

### CODE REVIEW

**Comment by Howuhh** [comment]
Hi @AlexPasqua! Thank you for the fix! 

These bugs from the differences between gym and gymnasium api. Also, can you increment seed in the eval for each reset (you can just add episode idx), so that each episode is different but the whole eval is deterministic for a particular starting seed?

After that I will merge!

**Comment by AlexPasqua** [comment]
> These bugs from the differences between gym and gymnasium api.

Yes, the package used in the code is technically still `gym`, but from version `0.26.0` they changed the API.
We might add a `requirements.txt` file specifying `gym>=0.26.0`.

> Also, can you increment seed in the eval for each reset (you can just add episode idx), so that each episode is different but the whole eval is deterministic for a particular starting seed?

Done it, is it ok?

**Comment by Howuhh** [comment]
@AlexPasqua yup, it's fine! I will add requirements later, tho we should move on to the gymnasium as gym is completely outdated now (even the last versions).

One more thing, we should detect done with the new api as `terminated or truncated` (new api is `state, reward, terminated, truncated, info`). With current fixes it is just `terminated` and episode will not reset or throw an error as `truncated` is also an episode ending.

**Comment by AlexPasqua** [comment]
> @AlexPasqua yup, it's fine! I will add requirements later

I added it already, but it might not be complete (as I used torch cpu for practicity of setup). In case you can add anything to it.

> tho we should move on to the gymnasium as gym is completely outdated now (even the last versions).

Yeah, we might do a release now, to fix in time the working version with the latest gym, and then another release supporting only Gymnasium. However, if you feel that the code wouldn't be much different between the 2 version, we can directly add the Gymnasium support on this PR.

> One more thing, we should detect done with the new api as `terminated or truncated` (new api is `state, reward, terminated, truncated, info`). With current fixes it is just `terminated` and episode will not reset or throw an error as `truncated` is also an episode ending.

Done it ✔️

**Comment by Howuhh** [comment]
Thank you very much @AlexPasqua! 

> However, if you feel that the code wouldn't be much different between the 2 version

It will be the same actually! All breaking changes from gym>0.26 are present in the gymnasium as well.

**Comment by AlexPasqua** [comment]
> Thank you very much @AlexPasqua!
> 
> > However, if you feel that the code wouldn't be much different between the 2 version
> 
> It will be the same actually! All breaking changes from gym>0.26 are present in the gymnasium as well.

True, I just changed `import gym` to `import gymnasium as gym`.

**Comment by Howuhh** [comment]
Cool! LGTM

**Pull request merged**
